#!/bin/bash
#set -e

source ${OPENSHIFT_REPO_DIR}upgrade/versions
source ${OPENSHIFT_REPO_DIR}upgrade/nginx.sh
source ${OPENSHIFT_REPO_DIR}upgrade/php.sh

prepare_ndep
install_nginx
clear_usr
install_dephp
install_php
loadup_settings
cleanup