#!/bin/bash
#
# This is the MAKE script which makes PHP and other necessary stuffs.
#

## VERSIONS OF NGINX & PHP

export NGINX_VERSION='1.11.10'
export PHP_VERSION='7.0.16'
export MYSQL_VERSION='5.6.34'

## VERSIONS OF DEPENDENCIES

export PCRE_VERSION='8.40'
export OPENSSL_VERSION='1.0.2k'
export ZLIB_VERSION='1.2.11'
export ICU_VERSION=("58.2" "58_2");
export RE2C_VERSION='0.16'
export MCRYPT_VERSION='2.5.8'
export LIBTOOL_VERSION='2.4.6'
export BISON_VERSION='2.7.1'

## DOWNLOAD LINKS

export NGINX_LINK=http://nginx.org/download/
export PHP_LINK=http://php.net/distributions/
export MYSQL_LINK=http://dev.mysql.com/get/Downloads/
export PCRE_LINK=https://ftp.pcre.org/pub/pcre/
export OPENSSL_LINK=https://www.openssl.org/source/
export ZLIB_LINK=https://downloads.sourceforge.net/project/libpng/zlib/
export ICU_LINK=http://download.icu-project.org/files/icu4c/
export RE2C_LINK=https://github.com/skvadrik/re2c/releases/download/
export MCRYPT_LINK=https://downloads.sourceforge.net/project/mcrypt/Libmcrypt/
export LIBTOOL_LINK=http://ftp.gnu.org/gnu/libtool/
export BISON_LINK=http://ftp.gnu.org/gnu/bison/